//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.02 at 10:05:17 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/comparison/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nextep.designer.headless.standalone.model.xml;
